services:
  app:
    build:
      dockerfile: Dockerfile
    image: app
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
