openapi: 3.0.0
info:
  title: FileSystem DB API
  version: 1.0.0
  description: API documentation for FileSystem DB operations
  contact:
    name: API Support
    url: 'dreywesson.netlify.com'
    email: dreywesson@gmail.com
